language: android

sudo: false

android:
  components:
    - build-tools-27.0.3
    - android-22
    - extra-android-m2repository
    - extra-android-support
script:
  - ./gradlew assembleRelease
  deploy:
    provider: releases
    api_key:
      secure: aa7ae2c6b60a07deaef08c4fd48db92e62f55c1d
    file: Monitor/build/outputs/apk/release/Monitor-release.apk
    skip_cleanup: true
    on:
      tags: true


notifications:
  email:
  - apples398@gmail.com